### ISSUE TITLE
Allow speedtest.conf settings

### ISSUE THREAD

**Issue by ail1020** [arevindh/AdminLTE#12]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`5`

---
**Expected behaviour:**

`Ability to configure the location of the db as well as how long to keep historical data (similar to pihole-FTL.conf). Would be useful in order to limit the size the db takes up as well as the location in case someone wanted the db stored off the SD card and on a USB/network drive for example. Maybe use setupVars.conf?`

**Actual behaviour:**

`no configuration of such settings.`

**Steps to reproduce:**

`Not applicable`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`Not applicable`

**Troubleshooting undertaken, and/or other relevant information:**

`tried to locate documentation for configuration. Would expect a template for such configurations to exist here: https://github.com/arevindh/pi-hole/tree/master/advanced/Templates`

**Comment by ail1020** [comment]
I decided to give it a shot. I did fairly limited testing though. Made sure it purged old records when running speedtest.sh and used a custom db file in the same default directory. Also not sure what'll happen if the SPEEDTEST_DB variable is something other than .db

**Comment by arevindh** [comment]
@ail1020 wow great will check it today itself
