### ISSUE TITLE
Can't update Pi-hole admin-LTE to 4.3.2

### ISSUE THREAD

**Issue by Natizyskunk** [arevindh/AdminLTE#19]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

8

---

**Expected behaviour:**

We should be able to get the speedtest mod on the latest official pi-hole admin-LTE web interface update

**Actual behaviour:**

When moving admin folder to org_admin and cloning the speedtest-mod admin folder, the latest web interface version 4.3.2 can't be installed even if the messdage "update available" is showing on the web interface.

**Steps to reproduce:**

1. Clone latest Official pi-hole 'admin' folder inside /var/www/html/.
2. Update webscripts file inside /opt/pihole/ with the speedtest-mod webpage.sh script.
3. Move original pihole 'admin' to 'org_admin' folder inside /var/www/html/.
4. Clone new speedtest-mod admin folder inside /var/www/html.
5. Now when checking the web interface; you can see the update message showing up but you can't update.

**Troubleshooting undertaken, and/or other relevant information:**

1. Reverting everything to official pi-hole (webscripts file 'webpage.sh' and 'admin' folder).
2. Copy official pi-hole 'admin' folder to 'org_admin' folder inside /var/www/html/.
3. add the speedtest-mod repo as a 'mod' remote (co-existing with current pihole admin).
4. Copy latest speedtest.db available in var/www/html/admin/scripts/pi-hole/speedtest/ from speedtest-mod repo inside the 'pihole' folder inside /etc/.
5. Move official pi-hole webscripts file 'webpage.sh' to 'webpage.sh.org' inside the 'pihole' folder in /opt/.
6. Get the latest webscripts file 'webpage.sh' from the speedtest repo.
7. Fix conflicts inside the 'settings.php' file inside the 'admin' folder in /var/www/html/.
8. Voilà, you should be able to get the speedtest-mod with the latest official pi-hole 4.3.2 web interface (Admin-LTE).

**Comment by arevindh** [comment]
Updated

**Comment by Natizyskunk** [comment]
> Updated

Thanks ! :)
