### ISSUE TITLE
FEATURE REQUEST: View Speedtest results without being logged in

### ISSUE THREAD

**Issue by Intecpsp** [arevindh/AdminLTE#36]
By default only the "Total queries over last 24 hours" graph is shown when not logged in. This keeps the actual client data from being shown to unauthorized users. I believe the speedtest graph is safe enough to be shown without being logged in.

**Comment by arevindh** [comment]
@Intecpsp will add an extra option for this in next release

**Comment by arevindh** [comment]
Moving this to [arevindh/pihole-speedtest](https://github.com/arevindh/pihole-speedtest/issues)
