### ISSUE TITLE
`pihole -a -sn` broken

### ISSUE THREAD

**Issue by ail1020** [arevindh/AdminLTE#41]
When attempting to run `pihole -a -sn` it seems to be attempting to run `speedtest-cli` even though the command was changed to `speedtest`. This causes the command to fail.

**Comment by arevindh** [comment]
@ail1020  Please use https://github.com/arevindh/pihole-speedtest to submit issues . 

`pihole -a -sn` is depreciated . Check wiki for  new command https://github.com/arevindh/pihole-speedtest/wiki/Installing-Speedtest-Mod#test-pihole-speedtest-from-commandline

**Comment by ail1020** [comment]
Is it still required to pull in webpage.sh with updates in that case?
