### ISSUE TITLE
Results missing in speedTest

### ISSUE THREAD

**Issue by Zelphire** [arevindh/AdminLTE#6]
**In raising this issue, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/AdminLTE/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/AdminLTE/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/AdminLTE/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

Speedtest at regular intevels.

**Actual behaviour:**

Some speedtest results are not shown or are missing .

**Steps to reproduce:**

Schedule speedtest of any intervel  

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

-

**Troubleshooting undertaken, and/or other relevant information:**
Tried many Schedule settings but won't work correctly

**Comment by nnleaf** [comment]
Hi, I saw the same issue on google+.
I have a completely new pihole install and added the speedtest mod. I can run speedtest from the cli, but none of the results will show up on the webUI interface. Changing intervals doesn't do anything either. 

My debug code is : bypmlape48

**Comment by arevindh** [comment]
@nnleaf. Can you try directly running and check the UI.

`sudo /var/www/html/admin/scripts/pi-hole/speedtest/speedtest.sh`

For **debugging** please post the output of following commands

`php -v` 
`php -m`
`sqlite3 -version`

 ℹ️  Since I am just the mod developer, I cant access the debug token data.

**Comment by arevindh** [comment]
Fixed in 114f4c90828feefb87125ef2d77d3d46ffcfbfa3

**Comment by nnleaf** [comment]
Hi @arevindh I was missing sqlite3 on my pihole. 
Running `sudo apt install sqlite3` did the trick.

**Comment by arevindh** [comment]
Fixed in 114f4c90828feefb87125ef2d77d3d46ffcfbfa3
