### ISSUE TITLE
API not working correctly

### ISSUE THREAD

**Issue by Preisschild** [arevindh/AdminLTE#8]
For some reason your API (getSpeedData24hrs&PHP) does not work very well for me and if i try to curl it (curl 'http://localhost/admin/api.php?getSpeedData24hrs\&PHP') on my rpi I only get 
>[]

How to use your API?

**Comment by arevindh** [comment]
The request needs Authentication using API token

`curl 'http://localhost/admin/api.php?getSpeedData24hrs&PHP&auth=<tokenhere>'`
